"""
filter_donor.py

Filter donor programs for use in Hypothesmith.

Goals:
- Remove auto-generated code
- Keep only syntactically valid programs
- Remove exact duplicates
- Avoid empty/broken outputs

Outputs:
    directory/base_programs/donor_corpus/filtered

Example:
    python src/filter_donor.py
"""

import ast
import hashlib
import os
from pathlib import Path

INPUT_DIR = "directory/base_programs/donor_corpus/raw"
OUTPUT_DIR = "directory/base_programs/donor_corpus/filtered"

os.makedirs(OUTPUT_DIR, exist_ok=True)

# --------------------------------------------------
# Filter configuration
# --------------------------------------------------

MIN_FILE_LEN = 50
MAX_FILE_LEN = 50000

MIN_FUNC_BODY_STMTS = 3
MAX_FUNC_LEN = 10000

AUTO_GENERATED_KEYWORDS = [
    "generated automatically",
    "do not edit",
    "@generated",
    "auto-generated",
]

# --------------------------------------------------
# Statistics
# --------------------------------------------------

count = 0
skipped_invalid = 0
skipped_generated = 0
skipped_duplicate = 0
skipped_small_func = 0

# Used for duplicate removal
seen_hashes = set()

# --------------------------------------------------
# Helper functions
# --------------------------------------------------

def is_autogenerated(code: str) -> bool:
    lowered = code.lower()
    return any(keyword in lowered for keyword in AUTO_GENERATED_KEYWORDS)


def is_valid_python(code: str) -> bool:
    try:
        ast.parse(code)
        return True
    except Exception:
        return False


def hash_snippet(snippet: str) -> str:
    return hashlib.sha256(snippet.encode("utf-8")).hexdigest()


# --------------------------------------------------
# Main filtering loop
# --------------------------------------------------

for path in Path(INPUT_DIR).glob("*.py"):
    try:
        code = path.read_text(encoding="utf-8")

        # ------------------------------------------
        # File-level filtering
        # ------------------------------------------

        if len(code) < MIN_FILE_LEN or len(code) > MAX_FILE_LEN:
            continue

        if is_autogenerated(code):
            skipped_generated += 1
            continue

        if not is_valid_python(code):
            skipped_invalid += 1
            continue

        tree = ast.parse(code)

        # ------------------------------------------
        # Extract top-level functions only
        # ------------------------------------------

        for node in tree.body:

            # Keep only regular + async functions
            if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                continue

            # Require minimum structural complexity
            if len(node.body) < MIN_FUNC_BODY_STMTS:
                skipped_small_func += 1
                continue

            snippet = ast.unparse(node)

            # Skip gigantic functions
            if len(snippet) > MAX_FUNC_LEN:
                continue

            # Remove duplicates
            snippet_hash = hash_snippet(snippet)

            if snippet_hash in seen_hashes:
                skipped_duplicate += 1
                continue

            seen_hashes.add(snippet_hash)

            # --------------------------------------
            # Save filtered donor
            # --------------------------------------

            out_path = f"{OUTPUT_DIR}/func_{count}.py"

            with open(out_path, "w", encoding="utf-8") as f:
                f.write(snippet)

            count += 1

    except Exception:
        continue

# --------------------------------------------------
# Summary
# --------------------------------------------------

print(f"Saved functions:        {count}")
print(f"Skipped invalid:        {skipped_invalid}")
print(f"Skipped autogenerated:  {skipped_generated}")
print(f"Skipped duplicates:     {skipped_duplicate}")
print(f"Skipped trivial funcs:  {skipped_small_func}")